/* DoubleYou Versus — data-driven characters, ranks, store, mastery.
   Combat + Character Info both read from CHARACTERS. */
(function (g) {
  const RANKS = [
    { id: "unranked", name: "UNRANKED", minCp: -1, quota: 0, reward: "Starting rank" },
    { id: "rookie", name: "ROOKIE", minCp: 0, quota: 100, reward: "Rookie title + 25 W Coins" },
    { id: "sidekick", name: "SIDEKICK", minCp: 100, quota: 200, reward: "Sidekick title + 50 W Coins" },
    { id: "vigilante", name: "VIGILANTE", minCp: 200, quota: 350, reward: "Vigilante title + 75 W Coins" },
    { id: "hero", name: "HERO", minCp: 350, quota: 500, reward: "Hero title + 100 W Coins" },
    { id: "superhero", name: "SUPERHERO", minCp: 500, quota: 650, reward: "Superhero title + 125 W Coins" },
    { id: "elite", name: "ELITE HERO", minCp: 650, quota: 900, reward: "Elite Hero title + 150 W Coins" },
    { id: "powerhouse", name: "POWERHOUSE", minCp: 900, quota: 1150, reward: "Powerhouse title + 200 W Coins" },
    { id: "legend", name: "LEGEND", minCp: 1150, quota: 1400, reward: "Legend title + 300 W Coins" },
    { id: "icon", name: "ICON", minCp: 1400, quota: 1700, reward: "Icon title + 400 W Coins" },
    { id: "godlike", name: "GODLIKE", minCp: 1700, quota: Infinity, reward: "Godlike title + 500 W Coins + leaderboard" },
  ];

  const MASTERY = [
    { id: "none", name: "NO MASTERY", kills: 0, rounds: 0, reward: "Starting mastery" },
    { id: "novice", name: "Novice", badge: "assets/badges/novice.jpg", kills: 0, rounds: 0, reward: "Novice title + 100 W Coins" },
    { id: "apprentice", name: "Apprentice", badge: "assets/badges/apprentice.jpg", kills: 100, rounds: 100, reward: "Apprentice title + 100 W Coins" },
    { id: "disciple", name: "Disciple", badge: "assets/badges/disciple.jpg", kills: 200, rounds: 200, reward: "Disciple title + 100 W Coins + character name banner" },
    { id: "combatant", name: "Combatant", badge: "assets/badges/combatant.jpg", kills: 300, rounds: 300, reward: "Combatant title + 100 W Coins + character banner frame" },
    { id: "expert", name: "Expert", badge: "assets/badges/expert.jpg", kills: 500, rounds: 500, reward: "Expert title + 100 W Coins + character profile picture" },
    { id: "master", name: "Master", badge: "assets/badges/master.jpg", kills: 700, rounds: 700, reward: "Master title + 100 W Coins" },
    { id: "grandmaster", name: "Grandmaster", badge: "assets/badges/grandmaster.jpg", kills: 900, rounds: 900, reward: "Grandmaster title + 100 W Coins" },
    { id: "monk-blue", name: "Blue Monk", badge: "assets/badges/monk_blue.jpg", kills: 1000, rounds: 1000, winPct: 0.40, reward: "Blue Monk title + 100 W Coins" },
    { id: "monk-purple", name: "Purple Monk", badge: "assets/badges/monk_purple.jpg", kills: 1000, rounds: 1000, winPct: 0.50, reward: "Purple Monk title + 100 W Coins. Drops a tier if win rate falls below 50%." },
    { id: "monk-yellow", name: "Yellow Monk", badge: "assets/badges/monk_yellow.jpg", kills: 1000, rounds: 1000, winPct: 0.60, reward: "Yellow Monk title + 100 W Coins. Drops a tier if win rate falls below 60%." },
  ];

  const POWER_PASS = {
    price: 4000,
    roundsPerLevel: 11,
    skins: {
      inferna: { id: "phoenix", name: "Phoenix Knight" },
      shade: { id: "midknight", name: "Mid-Knight" },
      lumen: { id: "bright", name: "Bright Knight" },
      tide: { id: "aqua", name: "Aqua Knight" },
      crown: { id: "queen", name: "Crown the Queen" },
      viper: { id: "serpent", name: "The King's Serpent" }
    },
    maxLevel: 10,
    levels: [
      { lv: 1, rounds: 11, reward: "Intro", kind: "intro", lock: "char" },
      { lv: 2, rounds: 22, reward: "Outro", kind: "outro", lock: "char" },
      { lv: 3, rounds: 33, reward: "Emote", kind: "emote", lock: "char" },
      { lv: 4, rounds: 44, reward: "2x CP Coin", kind: "cpcoin", lock: "account" },
      { lv: 5, rounds: 55, reward: "Profile Picture", kind: "pfp", lock: "char" },
      { lv: 6, rounds: 66, reward: "Basic Victory Pose", kind: "pose", lock: "char" },
      { lv: 7, rounds: 77, reward: "Banner Frame", kind: "frame", lock: "char" },
      { lv: 8, rounds: 88, reward: "Name Banner", kind: "banner", lock: "char" },
      { lv: 9, rounds: 99, reward: "Skin", kind: "skin", lock: "char" },
      { lv: 10, rounds: 110, reward: "Season Finalist Badge", kind: "finalist", lock: "account" }
    ]
  };

  const COSMETICS = [];
  const PAYPAL_EMAIL = "DoubleYou.Studio@outlook.com";
  const COIN_PACKS = [
    { id: "pack1000", coins: 1000, usd: "4.99", name: "1,000 W COINS" },
    { id: "pack2500", coins: 2500, usd: "9.99", name: "2,500 W COINS" },
    { id: "pack5000", coins: 5000, usd: "19.99", name: "5,000 W COINS" },
    { id: "pack10000", coins: 10000, usd: "39.99", name: "10,000 W COINS" },
  ];

  const SKINS = {
    inferna: [{ id: "default", name: "Basic Skin" }, { id: "phoenix", name: "Phoenix Knight", pass: 9 }],
    shade: [{ id: "default", name: "Basic Skin" }, { id: "midknight", name: "Mid-Knight", pass: 9 }],
    lumen: [{ id: "default", name: "Basic Skin" }, { id: "bright", name: "Bright Knight", pass: 10 }],
    tide: [{ id: "default", name: "Basic Skin" }, { id: "aqua", name: "Aqua Knight", pass: 10 }],
    crown: [{ id: "default", name: "Basic Skin" }, { id: "queen", name: "Crown the Queen", pass: 10 }],
    viper: [{ id: "default", name: "Basic Skin" }, { id: "serpent", name: "The King's Serpent", pass: 10 }],
  };
  const PRESENTATIONS = {
    victory: [
      { id: "basic", name: "Basic Victory Pose" },
      { id: "phoenix", name: "Basic Victory Pose", pass: 6, char: "inferna" },
      { id: "midknight", name: "Basic Victory Pose", pass: 6, char: "shade" },
      { id: "bright", name: "Basic Victory Pose", pass: 6, char: "lumen" },
      { id: "aqua", name: "Basic Victory Pose", pass: 6, char: "tide" },
      { id: "queen", name: "Basic Victory Pose", pass: 6, char: "crown" }
    ],
    intro: [
      { id: "basic", name: "Basic Intro" },
      { id: "phoenix", name: "Phoenix Knight Intro", pass: 1, char: "inferna" },
      { id: "midknight", name: "Mid-Knight Intro", pass: 1, char: "shade" },
      { id: "bright", name: "Bright Knight Intro", pass: 1, char: "lumen" },
      { id: "aqua", name: "Aqua Knight Intro", pass: 1, char: "tide" },
      { id: "queen", name: "Crown the Queen Intro", pass: 1, char: "crown" }
    ],
    outro: [
      { id: "basic", name: "Basic Outro" },
      { id: "phoenix", name: "Phoenix Knight Outro", pass: 2, char: "inferna" },
      { id: "midknight", name: "Mid-Knight Outro", pass: 2, char: "shade" },
      { id: "bright", name: "Bright Knight Outro", pass: 2, char: "lumen" },
      { id: "queen", name: "Crown the Queen Outro", pass: 2, char: "crown" },
      { id: "aqua", name: "Aqua Knight Outro", pass: 2, char: "tide" },
      { id: "serpent", name: "The King's Serpent Outro", pass: 2, char: "viper" }
    ],
    emote: [
      { id: "basic", name: "None" },
      { id: "pass", name: "Power Pass Emote", pass: 3 },
      { id: "flame", name: "Flame On", pass: 3, char: "inferna" },
      { id: "rift", name: "Rift Walker", pass: 3, char: "shade" },
      { id: "static", name: "Static Charge", pass: 3, char: "lumen" },
      { id: "downpour", name: "Downpour", pass: 3, char: "tide" },
      { id: "throne", name: "Throne Room", pass: 3, char: "crown" },
      { id: "serpentcoil", name: "Serpent Coil", pass: 3, char: "viper" },
      { id: "supernova", name: "Supernova", char: "inferna", bundle: "ult-legacy" },
      { id: "eclipse", name: "Eclipse", char: "shade", bundle: "ult-legacy" },
      { id: "thunderstrike", name: "Thunderstrike", char: "lumen", bundle: "ult-legacy" },
      { id: "tsunami", name: "Tsunami", char: "tide", bundle: "ult-legacy" },
      { id: "ironreign", name: "Iron Reign", char: "crown", bundle: "ult-legacy" },
      { id: "venomstorm", name: "Venom Storm", char: "viper", bundle: "ult-legacy" }
    ],
  };
  const PFPS = [
    { id: "inferna", name: "INFERNA", src: "assets/pfp/inferna.png", char: "inferna", unlock: "expert" },
    { id: "shade", name: "SHADE", src: "assets/pfp/shade.png", char: "shade", unlock: "expert" },
    { id: "lumen", name: "LUMEN", src: "assets/pfp/lumen.png", char: "lumen", unlock: "expert" },
    { id: "tide", name: "TIDE", src: "assets/pfp/tide.png", char: "tide", unlock: "expert" },
    { id: "crown", name: "CROWN", src: "assets/pfp/crown.png", char: "crown", unlock: "expert" },
    { id: "viper", name: "VIPER", src: "assets/pfp/viper.png", char: "viper", unlock: "expert" },
    { id: "pass-inferna", name: "INFERNA PASS", src: "assets/pass/pfp/inferna.jpg", char: "inferna", pass: 5 },
    { id: "pass-shade", name: "SHADE PASS", src: "assets/pass/pfp/shade.jpg", char: "shade", pass: 5 },
    { id: "pass-lumen", name: "LUMEN PASS", src: "assets/pass/pfp/lumen.jpg", char: "lumen", pass: 5 },
    { id: "pass-tide", name: "TIDE PASS", src: "assets/pass/pfp/tide.jpg", char: "tide", pass: 5 },
    { id: "pass-crown", name: "CROWN PASS", src: "assets/pass/pfp/crown.jpg", char: "crown", pass: 5 },
    { id: "pass-viper", name: "VIPER PASS", src: "assets/pass/pfp/viper.jpg", char: "viper", pass: 5 },
  ];

  const CHARACTERS = {
    inferna: {
      id: "inferna",
      name: "INFERNA",
      type: "Fire",
      weakness: "Water",
      health: 100,
      energy: 10,
      color: "#ff6a1a",
      color2: "#ffd36a",
      desc: "A fire-based fighter. Fast, aggressive, built to pressure and punish.",
      personality: "Fierce, relentless, theatrical.",
      style: "Rushdown / burn pressure",
      portrait: "assets/portrait_inferna.png",
      victory: "assets/select/inferna_panel.jpg",
      victoryVideo: "assets/victory/inferna.mp4",
      introVideo: "assets/intro/inferna.mp4",
      sheet: "assets/inferna.jpg",
      moves: [
        { id: "punch", name: "Fire Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Close-range fire punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "fireball", name: "Fireball", energy: 3, dmg: [5, 10], range: "long", stun: 0, input: "Hold Right Click + Left Click", desc: "Projectile toward cursor. Burns 5 dmg/sec for 4s." },
        { id: "upper", name: "Uppercut", energy: 3, dmg: [15, 20], range: "melee", stun: 0.18, input: "Hold Right Click + Up", desc: "Melee uppercut. Costs 3 energy. 15–20 damage. Pops the opponent up and knocks them back." },
        { id: "slam", name: "Fire Slam", energy: 4, dmg: [20, 30], range: "long", stun: 0.3, input: "Down while airborne", desc: "Slam to cursor X. Explosion on landing." },
        { id: "counter", name: "Counter Grab", energy: 3, dmg: [15, 30], range: "melee", stun: 0.5, input: "Hold Right Click + Down", desc: "Only if opponent is in a melee attack." },
        { id: "ult", name: "Ult of Fire", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "+50% damage on all Inferna attacks while active." },
        { id: "djump", name: "Double Jump", energy: 1, dmg: [0, 0], range: "none", stun: 0, input: "Up twice in air", desc: "Second jump costs 1 Energy." },
      ],
    },
    shade: {
      id: "shade",
      name: "SHADE",
      type: "Shadow",
      weakness: "Light",
      health: 100,
      energy: 10,
      color: "#9b5cff",
      color2: "#e8c6ff",
      desc: "Evasive shadow fighter. Teleports, hits from behind, vanishes.",
      personality: "Quiet, surgical, patient.",
      style: "Mix-up / backstab",
      portrait: "assets/portrait_shade.png",
      victory: "assets/select/shade_panel.jpg",
      victoryVideo: "assets/victory/shade.mp4",
      introVideo: "assets/intro/shade.mp4",
      sheet: "assets/shade.jpg",
      moves: [
        { id: "punch", name: "Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Basic melee punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "teleport", name: "Teleport", energy: 4, dmg: [0, 0], range: "none", stun: 0, input: "Hold Right Click + Up", desc: "Instant teleport to cursor." },
        { id: "kick", name: "Kick", energy: 3, dmg: [10, 20], range: "melee", stun: 0, input: "Hold Right Click + Left Click", desc: "Powerful kick with knockback." },
        { id: "push", name: "Shadow Push", energy: 3, dmg: [5, 15], range: "mid", stun: 0.3, input: "Hold Right Click + Right", desc: "Shadow blast, stun + knockback." },
        { id: "mode", name: "Shadow Mode", energy: 4, dmg: [0, 0], range: "none", stun: 0, input: "Hold Right Click + Down", desc: "2s invincible. Can still move and attack." },
        { id: "ult", name: "Ult of Shadows", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "Punch/Kick black out opponent 1s and heal Shade." },
      ],
      passive: "50% bonus damage when attacking from behind.",
    },
    lumen: {
      id: "lumen",
      name: "LUMEN",
      type: "Electric",
      weakness: "Elastic",
      health: 100,
      energy: 10,
      color: "#ffe14a",
      color2: "#fff6b0",
      desc: "Electric striker. Dashes, marks, and bursts with voltage.",
      personality: "Bright, cocky, precise.",
      style: "Dash / mark combo",
      portrait: "assets/portrait_lumen.png",
      victory: "assets/select/lumen_panel.jpg",
      victoryVideo: "assets/victory/lumen.mp4",
      introVideo: "assets/intro/lumen.mp4",
      sheet: "assets/lumen.jpg",
      moves: [
        { id: "punch", name: "Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Electric melee punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "dash", name: "Dash", energy: 4, dmg: [10, 15], range: "mid", stun: 0, input: "Hold Right Click + Left Click", desc: "Dash through the opponent. 10–15 damage on pass-through. Stops at the arena edge. +50% if target is Shock marked." },
        { id: "shock", name: "Shock", energy: 2, dmg: [5, 10], range: "melee", stun: 0.4, input: "Hold Right Click + Left/Right", desc: "Melee burst. Applies 2s Shock Marker." },
        { id: "faze", name: "Faze", energy: 3, dmg: [0, 0], range: "none", stun: 0, input: "Hold Right Click + Down", desc: "2s invincible. Cannot move." },
        { id: "multi", name: "Multi Punch", energy: 3, dmg: [20, 20], range: "melee", stun: 0.35, input: "Hold Right Click + Right", desc: "Flurry. 20 damage at the end of the animation." },
        { id: "ult", name: "Electric Empowerment", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "+15 Health. Opponent move speed −50% for 10s." },
      ],
    },
    tide: {
      id: "tide",
      name: "TIDE",
      type: "Water",
      weakness: "Electric",
      health: 100,
      energy: 10,
      color: "#3aa7ff",
      color2: "#b8ecff",
      desc: "Water controller. Shields, slows, and outlasts.",
      personality: "Calm, protective, implacable.",
      style: "Defense / attrition",
      portrait: "assets/portrait_tide.png",
      victory: "assets/select/tide_panel.jpg",
      victoryVideo: "assets/victory/tide.mp4",
      introVideo: "assets/intro/tide.mp4",
      sheet: "assets/tide.jpg",
      moves: [
        { id: "punch", name: "Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Water-laced punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "whip", name: "Water Whip", energy: 2, dmg: [6, 24], range: "mid", stun: 0, input: "Hold Right Click + Left Click", desc: "Mid-range water lash. Less damage up close, more at range." },
        { id: "shield", name: "Water Shield", energy: 4, dmg: [5, 5], range: "melee", stun: 0.5, input: "Hold Right Click + Down", desc: "25 HP shield for 2s. Break knocks melee foes." },
        { id: "wave", name: "Wave", energy: 3, dmg: [5, 5], range: "mid", stun: 0.3, input: "Hold Right Click + Left", desc: "Wave. Knockback + 50% slow for 3s." },
        { id: "wdash", name: "Water Dash", energy: 3, dmg: [0, 0], range: "mid", stun: 0, input: "Hold Right Click + Right", desc: "Dash backward. Heal 5." },
        { id: "ult", name: "Rainforest", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "Arena rains. Tide heals 3 HP/sec." },
      ],
    },
    crown: {
      id: "crown",
      name: "CROWN",
      type: "Magnetism",
      weakness: "Plant",
      health: 100,
      energy: 10,
      color: "#e8c46a",
      color2: "#fff1c2",
      desc: "Magnetic sovereign. Armor up, then slam.",
      personality: "Regal, composed, commanding.",
      style: "Armor / control",
      portrait: "assets/portrait_crown.png",
      victory: "assets/select/crown_panel.jpg",
      victoryVideo: "assets/victory/crown.mp4",
      introVideo: "assets/intro/crown.mp4",
      sheet: "assets/crown.jpg",
      moves: [
        { id: "punch", name: "Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Metal-edged punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "proj", name: "Metal Projectile", energy: 4, dmg: [15, 25], range: "long", stun: 0, input: "Hold Right Click + Left Click", desc: "1.5s throw. Costs 4 energy. Orb flies to the cursor from when the buttons were pressed." },
        { id: "shield", name: "Metal Shield", energy: 3, dmg: [0, 0], range: "none", stun: 0, input: "Hold Right Click + Down", desc: "1s invincible. Deflects projectiles toward cursor." },
        { id: "mode", name: "Metal Mode", energy: 6, dmg: [0, 0], range: "none", stun: 0, input: "Hold Right Click + Up", desc: "5s, 20% damage reduction. Unlocks Slam and Kick." },
        { id: "slam", name: "Metal Slam", energy: 3, dmg: [10, 15], range: "melee", stun: 1, input: "Hold Right Click + Left (Metal Mode)", desc: "Only in Metal Mode. 1s stun." },
        { id: "kick", name: "Kick", energy: 2, dmg: [10, 15], range: "melee", stun: 0, input: "Hold Right Click + Right (Metal Mode)", desc: "Only in Metal Mode. Knockback." },
        { id: "ult", name: "Magnetic Ascension", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "Fly + 30% damage reduction for 10s." },
      ],
    },
    viper: {
      id: "viper",
      name: "VIPER",
      type: "Plant",
      weakness: "Fire",
      health: 100,
      energy: 10,
      color: "#3adf4a",
      color2: "#c8ff9a",
      desc: "Plant / poison assassin. DoT, fangs, coils.",
      personality: "Playful, venomous, predatory.",
      style: "Poison / trap",
      portrait: "assets/portrait_viper.png",
      victory: "assets/select/viper_panel.jpg",
      victoryVideo: "assets/victory/viper.mp4",
      introVideo: "assets/intro/viper.mp4",
      sheet: "assets/viper.jpg",
      moves: [
        { id: "punch", name: "Punch", energy: 0, dmg: [5, 10], range: "melee", stun: 0, input: "Left Click", desc: "Venom-laced punch. Speeds melee animations." },
        { id: "rush", name: "DOWN", energy: 0, dmg: [0, 0], range: "none", stun: 0, input: "Down", desc: "Speeds up the current animation." },
        { id: "bite", name: "Venom", energy: 3, dmg: [12, 20], range: "short", stun: 1, input: "Hold Right Click + Left Click", desc: "Close-range fangs. Stuns 1s. No movement or buttons while stunned." },
        { id: "gasjump", name: "Gas Jump", energy: 3, dmg: [1, 5], range: "trap", stun: 0, input: "Hold Right Click + Down", desc: "High jump. Leaves gas for 3s that deals 1–5 damage per second." },
        { id: "mode", name: "Gas Mode", energy: 6, dmg: [1, 5], range: "trap", stun: 0, input: "Hold Right Click + Up", desc: "1.5s gas form. Costs 6 energy. 1–5 damage per second. Green trail lasts 1.5s." },
        { id: "dash", name: "Viper Kick Dash", energy: 3, dmg: [6, 10], range: "short", stun: 0, input: "Hold Right Click + Right", desc: "Short kick dash toward the cursor." },
        { id: "coil", name: "Spin Kick", energy: 4, dmg: [14, 24], range: "melee", stun: 1, input: "Hold Right Click + Left", desc: "Spinning kick. Stun 1s." },
        { id: "ult", name: "Viper's Wrath", energy: 10, dmg: [0, 0], range: "none", stun: 0, input: "Double Right Click (after 30s)", desc: "Poison opponent 8s. Heal 15 on activation." },
      ],
    },
  };

  const ARENAS = [
    { id: "citadel", name: "WRATH OF THE KNIGHT", mood: "dusk", video: "castle", blast: true, scroll: false, thumb: "assets/maps/wrath.jpg" },
    { id: "studio", name: "PROJECT WORKSITE", mood: "dusk", video: "studio", blast: false, scroll: false, thumb: "assets/maps/worksite.jpg" },
  ];

  g.DV = g.DV || {};
  g.DV.DATA = { RANKS, MASTERY, COSMETICS, CHARACTERS, ARENAS, SKINS, PRESENTATIONS, COIN_PACKS, PAYPAL_EMAIL, PFPS, POWER_PASS };
})(window);
